'''Each new term in the Fibonacci sequence is generated by adding 
the previous two terms. By starting with 1 and 2, the first 10 terms will be:
1, 2, 3, 5, 8, 13, 21, 34, 55, 89, ...
By considering the terms in the Fibonacci sequence whose values 
do not exceed four million, find the sum of the even-valued terms.'''

n1, n2 = 0, 1
count = 0
sums = 0
print("Fibonacci sequence:")
while (n2 < 4000000):
    nth = n1 + n2
    # update values
    n1 = n2
    n2 = nth
    count += 1
    print(n1 ,end =' ')       
    if(n1%2 == 0):
        sums+=n1
print("\nsum is ",sums)
